### PR TITLE
Issue87 plus all mi

### LINKED ISSUE #46: Move jurisdiction_path to run_time.ini
- Create a dictionary of the jurisdiction counts (senate, house, and congressional districts) for the JurisdictionPrepper class. 
- Print a warning informing that the jurisdiction counts are mostly right but might have to be verified against the information on the state board of elections. 
- Update the documentation.

### LINKED ISSUE #87: Take all system-specific info out of results.ini
Currently the `*.ini` file for each results file need a 'jurisdiction_path' parameter. This is path depends on the user's environment, which makes the `*.ini` file not portable without modification.

Since the path to the jurisdictions directory is now in `run_time.ini`, the jurisdiction_path parameter is redundant (except for the name (not path) of the jurisdiction itself. 

The `*.ini` file should use only the name of the jurisdiction folder, not the whole path. 

There will be backwards compatibility issues.

### LINKED ISSUE #97: (more than a comfortable amount of) repetition across config files
I doubt this is news to anyone - but there's definitely a lot of repetition of key directives across the various config files. 

For example, considering the 3 major `.ini` files for the PA configuration:

In both `pa18g.ini` and `jurisdiction_prep.ini`:
`munger_name=pa_gen`
`jurisdiction_path=/opt/verify/src/jurisdictions/Pennsylvania`
`results_file=/opt/verify/model/PA/data/2018g/Official_7232020043015PM.CSV`

And in both `jurisdiction_prep.ini` and `run_time.ini` we have:
`project_root=/opt/verify/src`

This are just obvious, "first-order" examples.  There are also cases of directives where we the variable names are different, even though they seem to be referring to the same thing - or are they?  It's not so easy to tell, e.g.:

`jurisdiction_prep.ini:name=Pennsylvania`
`pa18g.ini:top_reporting_unit=Pennsylvania`

And then there there cases of implicit repetition:  For example - we're pretty much *always* going to have the `jurisdictions` root directly under the `project_root` - and the state-level directory will hopefully *always* be named located directly under the the `jurisdictions` directory, and after the state[1] -- right?  In that case there's no need for a separate directive for the `jurisdiction_path`:

`jurisdiction_path=/opt/verify/src/jurisdictions/Pennsylvania`

BTW, I suppose that **some** of these repetitions may have a rationale -- but the point is there are *a lot* of repeated directives, and one can't *immediately* tell which have a purpose, and which are spurious.

I know these issues won't be fixed anytime soon - so I'm already applying the `low-priority` tag.  But they do add (unnecessary) confusion -- and in real terms, delay -- to the configuration process. 

[1] Actually, it should *always* be the 2-letter state code -- e.g. `jurisdictions/PA` - and not sometimes the 2-letter code, sometimes the full name like it is now.  But that's a separate issue.

### PR DESCRIPTION
**Pull request by sfsinger19103**
Closes #46 
Closes #87
Closes #97

- Allows a results.ini file to have only the name of the jurisdiction directory (jurisdiction_directory) rather than the entire path (with backward compatibility if instead the .ini file has the whole path (jurisdiction_path)
- Fixes a bug that repeated identical warning and error messages.
- Munges Michigan (2020 primary and presidential preference primary; 2018 general; 2016 general)
- Fixes many bugs (technical debt) for handling of results files with auxiliary data files (like MI 18g and 16g)

Supercedes pull request #91

### CODE REVIEW

**Comment by sfsinger19103** [comment]
Only one review needed.

**Comment by ericmtsai** [comment]
@sfsinger19103 I can't get this to load. It's a bit unclear to me exactly what to use (maybe the repo should be cleaned out a bit and/or renamed?). I landed on the `Michigan` jurisdiction file and tried both the `mi_gen_by_county` munger and the `mi_gen18` munger. The former gives me:
```
Munger errors (mi_gen_by_county):
Nothing read from datafile. Munger may be inconsistent, or datafile may be empty.
```

And the latter gives me:
```
Munger errors (mi_gen18):
Expected transformed column 'cit[City/Township Description]_SOURCE' not found, probably because of mismatch between munger and results file.
```

**Comment by sfsinger19103** [comment]
@ericmtsai Bug is now fixed. Use  `mi_gen_by_county`.

**Comment by ericmtsai** [comment]
@sfsinger19103 Still can't get data loaded, got this error now:
```
Munger errors (mi_gen_by_county):
Only 13 columns read from results file 2018vote.txt. Check file_type in format.config
```

results.ini file looks like this:
```
[election_data_analysis]
results_file=2018vote.txt
jurisdiction_directory=Michigan
munger_name=mi_gen_by_county
top_reporting_unit=Michigan
election=2018 General
results_short_name=mi_2018
results_download_date=09/16/2020
results_source=usually the State Board of Elections
results_note=Michigan State Board of elections
aux_data_dir=
```

Am I doing something wrong?

**Comment by sfsinger19103** [comment]
You need to specify the aux_data_dir where the supplementary files are stored. If you downloaded from the g-drive, that directory is `2018GEN`.

If that doesn't solve the problem, what are the contents of your `format.config` file and the first few lines of `2018vote.txt`?

**Comment by ericmtsai** [comment]
Complete user error. That did the trick. Thanks!

**Review by ericmtsai — APPROVED** [review]

**Pull request merged**
