### PR TITLE
Add michigan20p test

### PR DESCRIPTION
**Pull request by wonderbug2020**
Added a test file for Michigan 2020 primary. Tested against the database on VV server and they all passed!

### CODE REVIEW

**Comment by wonderbug2020** [comment]
I added a results.ini file however, this election has two files 2020PPR_MI_CENR_BY_COUNTY.XLS and 2020PRI_MI_CENR_BY_COUNTY.xls. I wasn't sure if (or how) I could add both of these to the same file or if I needed to make a second ini file for each result file

**Comment by ericmtsai** [comment]
@sfsinger19103 that comment above ^^^ is to you. I'm not sure either.

**Comment by sfsinger19103** [comment]
You'll need a second .ini file for the second result file.

**Review by sfsinger19103 — CHANGES_REQUESTED** [review]
Looks good. 

Please add mi20ppp.ini file and retest. Here's the contents that worked for me:
```[election_data_analysis]
results_file=2020PPR_MI_CENR_BY_COUNTY.xls
jurisdiction_directory=Michigan
munger_name=mi_pri_by_county
top_reporting_unit=Michigan
election=2020 Primary
results_short_name=mi_20ppp
results_download_date=2020-09-16
results_source=https://mielections.us/election/results/2020PPR_CENR.html
results_note=
aux_data_dir=
```

**Comment by sfsinger19103** [comment]
One test failed for me. Did it succeed for you @wonderbug2020 ? (Please tag me when you reply -- otherwise GitHub won't tell me you answered)
```
cps-urbn650c-pk:tests singer3$ python3 load_and_test_all.py -e '2020 Primary' -j 'Michigan'
['load_and_test_all.py', '-e', '2020 Primary', '-j', 'Michigan']
Election is 2020 Primary
Jurisdiction is Michigan
Tests will use data in existing directory: /Users/singer3/PycharmProjects/election_data_analysis/tests/TestingData
Directory already exists: /Users/singer3/PycharmProjects/election_data_analysis/src/jurisdictions/Michigan 
Loading jurisdiction from Michigan to Engine(postgresql://singer3:***@localhost:5432/test_1029_1323)
Processing results files ['mi20p.ini']
Munger initialized: mi_pri_by_county


Processing 2020PRI_MI_CENR_BY_COUNTY.xls

	Results uploaded with munger mi_pri_by_county to database Engine(postgresql://singer3:***@localhost:5432/test_1029_1323)
from file TestingData/2020PRI_MI_CENR_BY_COUNTY.xls
assuming jurisdiction /Users/singer3/PycharmProjects/election_data_analysis/src/jurisdictions/Michigan
mi20p.ini and its results file loaded successfully via mungers mi_pri_by_county.
Jurisdiction warnings written to /Users/singer3/Documents/Temp/010_loaded/test_1022_1212/mi20p_Michigan-mi_pri_by_county_1029_1323.warnings
Munger warnings written to /Users/singer3/Documents/Temp/010_loaded/test_1022_1212/mi20p_mi_pri_by_county_1029_1323.warnings

Ini errors (mi20ppp.ini):
Missing header: File contains no section headers.
file: 'TestingData/mi20ppp.ini', line: 1
'results_file=2020PPR_MI_CENR_BY_COUNTY.xls\n'


=================================== test session starts ====================================
platform darwin -- Python 3.8.5, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/singer3/PycharmProjects/election_data_analysis
collected 4 items                                                                          

test_Michigan_2020-Primary.py F...                                                   [100%]

========================================= FAILURES =========================================
____________________________ test_presidential[test_1029_1323] _____________________________

dbname = 'test_1029_1323'

    def test_presidential(dbname):
>       assert (e.contest_total(
                "2020 Primary",
                "Michigan",
                "US President (MI) (Democratic Party)",
                dbname=dbname,
            )
                == 1587679
        )
E       AssertionError: assert 0 == 1587679
E        +  where 0 = <function contest_total at 0x116df3a60>('2020 Primary', 'Michigan', 'US President (MI) (Democratic Party)', dbname='test_1029_1323')
E        +    where <function contest_total at 0x116df3a60> = e.contest_total

test_Michigan_2020-Primary.py:4: AssertionError
================================= short test summary info ==================================
FAILED test_Michigan_2020-Primary.py::test_presidential[test_1029_1323] - AssertionError:...
=============================== 1 failed, 3 passed in 2.76s ================================

```

**Pull request merged**
