### PR TITLE
Munge oh 2020g

### PR DESCRIPTION
**Pull request by bloy86**
Created new munger for Ohio 2020 General (oh_gen20) due to slight changes in file structure/naming between 2020 and other general elections.  Additions to dictionary as well, due to changes in naming.  

2 of the tests do not pass (see screenshot here) but the error is one I am not familiar with and/or it does not have to do with the Ohio data itself.  Please add comments and/or send back if I can make changes so that all tests pass.  Thanks!
Ohio Tests

### CODE REVIEW

**Comment by sfsinger19103** [comment]
The problem with the first failed test is the comma in `total_cd_votes = 385,285`.  This line instructs python to set `total_cd_votes` to the tuple `(385, 285)`.

The problem with the second failed test is that some candidate names are not recognized. You'll find the problematic candidates in the `.warnings` file:
``` Partys not found in dictionary.txt:
WI
Tom Roll <- did not match regex ^.* \((.*)\)[^\)\n]*$Tom Roll
Howie Hawkins and Angela Walker <- did not match regex ^.* \((.*)\)[^\)\n]*$Howie Hawkins and Angela Walker

Candidates not found in dictionary.txt:
Tom Roll <- did not match regex ^(.*) \(.*\)[^\)\n]*$Tom Roll
Howie Hawkins and Angela Walker <- did not match regex ^(.*) \(.*\)[^\)\n]*$Howie Hawkins and Angela Walker
```

**Comment by bloy86** [comment]
@sfsinger19103 The first problem was easy to fix but the second one has been difficult.  I added both Tom Roll and Howie Hawkins and Angela Walker to the dictionary, but that did not work.  I did notice that all candidates had the party in parentheses after their name (e.g., John Smith (D)) but these candidates with errors did not.  I did try to add party manually to the xlsx (bad practice I know) but this did not work either.  I included both the text of the failed test and the the .warnings file.  Happy to try any other ideas you may have.  Thanks!
Failed Ohio Test
[oh20g_Ohio-oh_gen20_1215_1844 copy.warnings.txt](https://github.com/ElectionDataAnalysis/election_data_analysis/files/5700027/oh20g_Ohio-oh_gen20_1215_1844.copy.warnings.txt)

**Comment by sfsinger19103** [comment]
It's an issue with the regex -- it expects parentheses after the person's name. I don't have the bandwidth to fix it right now. If you wanted to play around with regex, you could try adding those two names explicitly to the regex. The regexes in the Alaska mungers in the `issues-284-269-164-munger-params` might be instructive -- especially the one that picks up vote types.  Otherwise, leave this and move on. Thanks!

**Comment by sfsinger19103** [comment]
Ohio munged via NIST-format xml. No need to munge it another way

**Pull request closed without merging**
