### PR TITLE
Illinois add

### PR DESCRIPTION
**Pull request by wonderbug2020**
To my knowledge, this is a completed task for Illinois. Would welcome feedback on any changes needed or general suggested improvements

### CODE REVIEW

**Comment by ericmtsai** [comment]
Nice work @wonderbug2020 ! Did you try loading this into a DB? If not, please go ahead and do so, then write the tests for them in `tests/test_dataloader.py`. You can reference this ticket for some guidance, or ask me or @bloy86 if you have any questions: https://github.com/ElectionDataAnalysis/election_data_analysis/issues/85

Moving forward, we'll want to include these tests one a new state is processed.

**Comment by sfsinger19103** [comment]
@wonderbug2020 thanks for this progress. A bit more to do.

- remove all double quotes from Candidate.txt and corresponding lines in Dictionary.txt (Replace necessary ones with single quotes.)
- add IL Comptroller and IL Secretary of State to the Office file.

**Comment by wonderbug2020** [comment]
Requested changes made and have verified that the results can be loaded into the db

**Comment by ericmtsai** [comment]
@wonderbug2020 this still isn't working for me. I tried loading 2020 Primary data and the process completed without errors/warnings, but no data was loaded. Did you actually check your DB for data?

**Pull request closed without merging**
