### PR TITLE
Munge tx 2020

### PR DESCRIPTION
**Pull request by ericmtsai**
Munges 2020 Primary for Texas

### CODE REVIEW

**Comment by ericmtsai** [comment]
Added 2020 primary candidates and munger, however it's not mapping the data files to the correct version of the contest yet (for example, `US President (Democratic Party)`). Need to fix this before merging.

**Comment by ericmtsai** [comment]
@sfsinger19103 can you take a look at this? It seems like it's failing on `ROQUE "ROCKY" DE LA FUENTE`, who is in the files correctly as far as I can tell. Can't figure out what's going on.

**Comment by ericmtsai** [comment]
Note to self: found an error in the dictionary, with single vs double quotes

**Comment by sfsinger19103** [comment]
Munged and tested 2020 Primary

**Pull request merged**
